version: '3.5'

services:
    postgres:
        container_name: pg
        image: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: mycontacts
        volumes:
